version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "teatro"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "eliasamarante27@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "80:80"
    depends_on:
      - postgres
  

